In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.4.1'

In [4]:
tensor =tf.constant([[23,4],[32,51]])

In [5]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [8]:
tensor.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>>

In [10]:
session =tf.session()

AttributeError: ignored

In [ ]:
session.run(tf.global_variable_initializer())
tensor_value =session.run(tensor)
tensor_value

In [11]:
variable =tf.Variable([[30,20],[10,45]])
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[30, 20],
       [10, 45]], dtype=int32)>

In [12]:
variable.eval

<bound method BaseResourceVariable.eval of <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[30, 20],
       [10, 45]], dtype=int32)>>

In [ ]:
session=tf.Session()
session.run(tf.global_variable_initializer())
variable.eval(session)



In [13]:
tensor_20 =tf.constant([[23,4],[43,23]])

In [14]:
tensor_20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [43, 23]], dtype=int32)>

In [15]:
tensor_20.shape

TensorShape([2, 2])

In [16]:
tensor_20.numpy()

array([[23,  4],
       [43, 23]], dtype=int32)

In [18]:
import numpy as np
numpy_tensor=np.array([[23,4],[32, 43]])

In [19]:
tensor_from_numpy =tf.constant(numpy_tensor)

In [20]:
tensor_from_numpy

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[23,  4],
       [32, 43]])>

In [25]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [26]:
tf2_variable[0,2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [27]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [29]:
tensor=tf.constant([[1,2],[3,4]])

In [30]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [31]:
tensor+2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [32]:
tensor*5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

In [34]:
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [35]:
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [36]:
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [37]:
np.dot(tensor, tensor_20)

array([[109,  50],
       [241, 104]], dtype=int32)

In [38]:
tf_string=tf.constant("Tensorflow")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'Tensorflow'>

In [40]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [41]:
tf.strings.unicode_decode(tf_string , "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114, 102, 108, 111, 119], dtype=int32)>

In [46]:
tf_string_array=tf.constant(["Tensorflow", "Deep learning", " AI"])

for string in tf_string_array:
  print(string)


tf.Tensor(b'Tensorflow', shape=(), dtype=string)
tf.Tensor(b'Deep learning', shape=(), dtype=string)
tf.Tensor(b' AI', shape=(), dtype=string)
